# Generated by Django 4.2.27 on 2026-01-29 20:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_count', models.IntegerField()),
                ('avg_flowrate', models.FloatField()),
                ('avg_pressure', models.FloatField()),
                ('avg_temperature', models.FloatField()),
                ('type_distribution', models.JSONField()),
                ('data', models.JSONField()),
            ],
            options={
                'verbose_name': 'Equipment Dataset',
                'verbose_name_plural': 'Equipment Datasets',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
